---
name: 'CI'
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '*'
jobs:
  terraform-fmt:
    name: 'terraform-fmt'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'sharksRus/github-actions'
          path: '.github/actions'
          ref: 'main'
      - name: 'running terraform-fmt'
        uses: './.github/actions/terraform-fmt'

  tfsec:
    name: 'tfsec'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'sharksRus/github-actions'
          path: '.github/actions'
          ref: 'main'
      - name: 'running tfsec'
        uses: './.github/actions/tfsec'

  tflint:
    name: 'tflint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - name: 'Checkout GitHub actions repo'
        uses: 'actions/checkout@v2'
        with:
          repository: 'sharksRus/github-actions'
          path: '.github/actions'
          ref: 'main'
      - name: 'running tflint'
        uses: './.github/actions/tflint'

  yamllint:
    name: 'yamllint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@master'
        with:
          config_file: '.yamllint'
